blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^(?P<blog_id>\d+)/$',
        views.single_blog,
        name='view_single_blog'),

    url(r'^$',
        views.all_blogs,
        name='view_all_blogs'),

    url(r'^new/$',
        views.new_blog,
        name='view_new_blog'),

    url(r'^subscribe/$',
        views.subscribe,
        name='view_subscribe'),
]

pystagram/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import login, logout
from photo.views import single_photo, new_photo
from contact.views import new_contact
from .views import register

urlpatterns = [
    # photos
    url(r'^photo/(?P<photo_id>\d+)$', single_photo, name='view_single_photo'),
    url(r'^photo/upload/$', new_photo, name='new_photo'),

    # login, out
    url(r'^accounts/login/', login, name='login',
        kwargs={
            'template_name': 'login.html',
        }
    ),
    url(r'^accounts/logout/', logout, {'next_page': '/blog/'}, name='logout'),

    # register
    url(r'^accounts/register/', register, name='view_register'),

    # admin
    url(r'^admin/', admin.site.urls),

    # profiles
    url(r'^user/', include('profiles.urls')),

    # blog
    url(r'^blog/', include('blog.urls')),

    # github social login
    url('', include('social.apps.django_app.urls', namespace='social')),

    # contact
    url(r'^contact/', new_contact, name='view_new_contact'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contact/models.py
from __future__ import unicode_literals
from django.db import models
from django.conf import settings
from django.core.urlresolvers import reverse_lazy


class Contact(models.Model):
    class Meta:
        ordering = ['-created_at']

    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    title = models.CharField(max_length=200)
    body = models.TextField(max_length=500, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

contact/forms.py
from __future__ import unicode_literals
from django import forms
from .models import Contact


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ('title', 'body')

contact/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .forms import ContactForm


# make new contact
@login_required
def new_contact(request):
    if request.method == 'GET':
        new_form = ContactForm()
    elif request.method == 'POST':
        new_form = ContactForm(request.POST)

        if new_form.is_valid():
            new_contact = new_form.save(commit=False)
            new_contact.user = request.user
            new_contact.save()
            return redirect('/blog/')

    return render(request, 'new_contact.html', {
        'form': new_form,
    })

contact/templates/new_contact.html
{% extends 'layout.html' %}
{% load staticfiles %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/contact.css' %}">
{% endblock %}
{% block content %}

    {% if form.errors %}
        {{ form.errors }}
    {% endif %}

    <div class="contact">
        <h2>의견을 들려주세요</h2>
        <h5>새로 등록 됐으면 하는 블로그, 혹은 기능을 알려주세요</h5>
    </div>

    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6 contact-form">
            <form
                    method="POST"
                    action="{% url 'view_new_contact' %}"
                    enctype="multipart/form-data">
                {% csrf_token %}
                <p><label for="id_title">Title</label></p>
                <p><input id="id_title" maxlength="200" name="title" type="text" size="40" required/></p>
                <p><label for="id_body">Body</label></p>
                <p><textarea cols="40" id="id_body" maxlength="500" name="body" rows="10"></textarea></p>

                <button class="btn btn-lg btn-primary" type="submit">의견 보내기</button>
            </form>
        </div>
        <div class="col-md-3"></div>
    </div>

{% endblock %}